import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  { href: "/", label: "Home" },
  { href: "/static", label: "Static" },
  { href: "/server", label: "Server" },
  { href: "/edge", label: "Server (edge)" },
  { href: "/server?leak", label: "Leak" },
  { href: "/edge?leak", label: "Leak (edge)" },
  { href: "/server-actions", label: "Server Actions" },
  { href: "/api", label: "API (safe)" },
  { href: "/api?leak", label: "API (leaked!)" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-4 px-6 py-3 bg-zinc-100 dark:bg-zinc-900 text-sm font-mono border-b border-zinc-200 dark:border-zinc-800 flex-wrap">
          {navLinks.map(({ href, label }) => (
            <Link
              key={href}
              href={href}
              className="hover:underline text-blue-600 dark:text-blue-400"
            >
              {label}
            </Link>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
